# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
    - bash: echo fdfdfd


- stage: Devdeploy
  variables:
    environment: Dev
  dependsOn:
  - Build
  jobs:
  - job: Devdeployjob
    steps:
    - bash: echo  deplo job
    - bash: ls -R ${build.artifactstagingdirectory}
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: |
          **/*.yaml
          **/*.tf
        TargetFolder: '$(build.artifactstagingdirectory)'

